# Sistemas Lineares, Erros e Aritmética de Pontos Flutuantes


Nesse notebook será desenvolvido o projeto que irá responder os desafios propostos na Atividade 01 de MS211 - Cálculo Numérico

## Instalação de Bibliotecas


In [1]:
%pip install numpy
%pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## Importando bibliotecas

In [2]:
import numpy as np
import scipy

### Questão 1

Considerando o sistema linear $Ax = b$, em que
$$A = \begin{bmatrix} 0.1 & 0.2 & 0.3 \\ 0.4 & 0.5 & 0.6 \\ 0.7 & 0.8 & 0.9 \end{bmatrix}, \quad b = \begin{bmatrix} 0.1 \\ 0.3 \\ 0.5 \end{bmatrix}$$

In [3]:
A = np.array([[0.1, 0.2, 0.3], 
              [0.4, 0.5, 0.6], 
              [0.7, 0.8, 0.9]])
b = np.array([[0.1],[0.3],[0.5]])

Uma matriz é dita singular quando ela não possui inversa, isso também pode ser interpretado como o determinante dessa matriz sendo igual a 0. <br>
Abaixo, vemos que o determinante é muito próximo de 0.

In [4]:
det_A = np.linalg.det(A)
det_A

6.661338147750926e-18

#### Item A)

Como o cálculo do determinante de uma matriz envolve produtos de pivôs, primeiro vamos alterar essa matriz para que não aconteçam erros devido a pontos flutuantes.<br>
Sabe-se que se uma matriz B puder ser escrita como B = $k^n$*A, com k sendo escalar, n sendo a dimensão da matriz e A uma matriz de mesma dimensão que B, então o determinante da matriz B será

$$ det(B) = k^n*det(A) $$

Vamos dizer que a matriz B auxiliar será B = 10*A


In [5]:
B = 10*A
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Daí então, calcula-se o determinante da matriz B

In [6]:
det_B = np.linalg.det(B)
det_B

0.0

Ou seja, det(B) = 0 = $10^3$*det(A), logo det(A) = 0. <br>
Como a matriz A é singular, o sistema pode ser inconsistente, ou consistente com infinitas soluções. Para analisar isso, vemos o posto das duas matrizes.

In [7]:
rank_A = np.linalg.matrix_rank(A)
Ab = np.hstack((A, b.reshape(-1, 1)))
rank_Ab = np.linalg.matrix_rank(Ab)
if rank_Ab == rank_A:
    print("Sistema Consistente")
else:
    print("Sistema Inconsistente")

Sistema Consistente


Como o posto de A é igual ao posto da matriz aumentada $A | b$, então o sistema é consistente, logo possui infinitas soluções.<br>
O conjunto solução é do tipo 
$$ x = x_p + t v, \quad t \in \mathbb{R} $$

In [8]:
sol_particular, _, _, _ = np.linalg.lstsq(A, b, rcond=None)
nucleo = scipy.linalg.null_space(A)
sol_particular, nucleo

(array([[0.38888889],
        [0.22222222],
        [0.05555556]]),
 array([[-0.40824829],
        [ 0.81649658],
        [-0.40824829]]))

Nesse caso "sol_particular" é o $xp$ e "nucleo" é a base ortonormal $v$ para o espaço A

#### Item B)


Com aritmética exata, o método falha quando o último pivô é 0.<br>
Vamos verificar os pivôs da decomposição LU

In [9]:
P, L, U = scipy.linalg.lu(A)
np.diag(U)

array([7.00000000e-01, 8.57142857e-02, 1.11022302e-16])

Fazendo eliminação direta em aritmética exata sobre a matriz inteira 𝐵 (proporcional a 𝐴): <br>
Pivot $𝑎_{11} = 1$. Eliminar abaixo:<br>
$𝑅_2 ← 𝑅_2 − 4*𝑅_1 ⇒ [0, −3, −6]$<br>
$𝑅_3 ← 𝑅_3 − 7*𝑅_1 ⇒ [0, −6, −12]$<br>
Pivot na segunda etapa é −3 (não zero). Eliminar abaixo:
$𝑅_3 ← 𝑅_3 −2*𝑅_2 ⇒ [0, 0, 0]$

Agora restou uma linha zero; ao tentar usar essa linha como terceiro pivot, ele seria 0 — não há pivô e o processo não consegue obter uma matriz triangular com pivôs não-nulos para voltar a uma solução única. Portanto não é possível avançar na eliminação ao tentar obter o terceiro pivô (o sistema é singular), o que indica número infinito de soluções (ou inconsistência, se a linha zero viesse acompanhada de termo independente não-zero).<br>

Com pivoteamento parcial não se evita essa situação porque as linhas são proporcionais de modo que o terceiro pivô será zero: não há um elemento não nulo útil para o terceiro pivô.

#### Item C)

In [10]:
x_num = np.linalg.lstsq(A, b, rcond=None)[0]
x_num

array([[0.38888889],
       [0.22222222],
       [0.05555556]])